# Generated by Django 3.0.6 on 2020-06-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20180609_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingtype',
            options={'ordering': ('name',), 'verbose_name': 'Type of Building', 'verbose_name_plural': 'Types of Building'},
        ),
        migrations.AlterModelOptions(
            name='saletype',
            options={'ordering': ('name',), 'verbose_name': 'Type of Sale', 'verbose_name_plural': 'Types of Sale'},
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_1',
            field=models.ImageField(upload_to='media/property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/property'),
        ),
    ]
